e_shastho/Models/CoronaUpdateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e_shastho.Models
{

        public class CoronaUpdateModel
        {
            public CoronaUpdateModel()
            {

            }
            public CoronaUpdateModel(CoronaUpdateModel coronaUpdateModel)
            {
                this.Date = coronaUpdateModel.Date;
                this.ActiveCases = coronaUpdateModel.ActiveCases;
                this.NewDailyCases = coronaUpdateModel.NewDailyCases;
                this.NewDailyDeaths = coronaUpdateModel.NewDailyDeaths;
                this.TotalCases = coronaUpdateModel.TotalCases;
                this.TotalDeaths = coronaUpdateModel.TotalDeaths;
                this.TotalRecoveries = coronaUpdateModel.TotalRecoveries;
            }

            public DateTime? Date { get; set; }
            public int ActiveCases { get; set; }
            public int NewDailyCases { get; set; }
            public int NewDailyDeaths { get; set; }
            public int TotalCases { get; set; }
            public int TotalRecoveries { get; set; }

            public int TotalDeaths { get; set; }
        }
   }

e_shastho/Models/CoronaWorldWideUpdateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e_shastho.Models
{
    public class CoronaWorldWideUpdateModel:CoronaUpdateModel
    {
        public CoronaWorldWideUpdateModel()
        {

        }
        public CoronaWorldWideUpdateModel(CoronaUpdateModel coronaUpdateModel)
            : base(coronaUpdateModel) { }
        public string Country { get; set; }
    }
}

e_shastho/Controllers/CoronaUpdateController.cs
using e_shastho.Models;
using e_shastho.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace e_shastho.Controllers
{
    public class CoronaUpdateController : Controller
    {
        private CoronaLocalJSONService coronaLocalUpdateService = new CoronaLocalJSONService();
        private CoronaWorldWideUpdateService coronaWorldWideUpdateService = new CoronaWorldWideUpdateService();

        // GET: CoronaUpdate
        public ActionResult Index()
        {
            List<CoronaUpdateModel> coronaUpdates = new List<CoronaUpdateModel>();
            coronaUpdates = coronaLocalUpdateService.GetCoronaLocalUpdate();
            return View(coronaUpdates);
        }

        public async Task<ActionResult> WorldUpdate()
        {
            List<CoronaWorldWideUpdateModel> coronaUpdates = new List<CoronaWorldWideUpdateModel>();
            coronaUpdates = await coronaWorldWideUpdateService.GetWorldWideUpdate();
            return View(coronaUpdates);
        }
    }
}

e_shastho/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_shastho.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

e_shastho/Controllers/HospitalController.cs
using e_shastho.Data;
using e_shastho.Services;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace e_shastho.Controllers
{
    public class HospitalController : Controller
    {

        HospitalService hospitalService = new HospitalService();
        public ActionResult Index()
        {
            List<Hospital> hospitals =  hospitalService.GetHospitals();
            return View(hospitals);
        }

        public ActionResult MapLocator()
        {
            List<Hospital> hospitals = hospitalService.GetHospitals();
            return View(hospitals);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hospital model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            hospitalService.SaveHospital(model);

            return RedirectToAction(nameof(Index));
        }

    }
}

e_shastho/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using e_shastho.Data;
using e_shastho.Services;

namespace e_shastho.Controllers
{
    public class InfoController : Controller
    {
        InfoService infoService = new InfoService();
        // GET: Info
        public ActionResult Index()
        {
            List<Advice> advices = infoService.GetAdvices();
            return View(advices);
        }

        public ActionResult Details(int id)
        {
            Advice advice = infoService.GetDetails(id);
            return View(advice);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Advice model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            infoService.SaveAdvice(model);

            return RedirectToAction(nameof(Index));
        }
    }
}

e_shastho/Controllers/PlasmaDonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using e_shastho.Data;
using e_shastho.Services;

namespace e_shastho.Controllers
{
    public class PlasmaDonorController : Controller
    {
        PlasmaDonorService plasmaDonorService = new PlasmaDonorService();
        // GET: PlasmaDonor
        public ActionResult Index()
        {
            List<PlasmaDonor> plasmaDonors = plasmaDonorService.GetPlasmaDonors();
            return View(plasmaDonors);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlasmaDonor model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            plasmaDonorService.SavePlasmaDonor(model);

            return RedirectToAction(nameof(Index));
        }
    }
}

e_shastho/Controllers/TestLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using e_shastho.Data;
using e_shastho.Services;

namespace e_shastho.Controllers
{
    public class TestLocationController : Controller
    {
        TestLocationService testLocationService = new TestLocationService();
        // GET: TestLocation
        public ActionResult Index()
        {
            List<TestLocation> testLocations =  testLocationService.GetTestLocations();
            return View(testLocations);
        }

        public ActionResult MapLocator()
        {
            List<TestLocation> testLocations = testLocationService.GetTestLocations();
            return View(testLocations);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TestLocation model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            testLocationService.SaveTestLocation(model);

            return RedirectToAction(nameof(Index));
        }
    }
}

e_shastho/Views/Home/About.cshtml
@{
    ViewData["Title"] = "ডেভেলাপার পরিচিতি";
}


<div class="text-left">
    <h4 class="text-center">ডেভেলাপার পরিচিতি</h4>
    <hr />
    <p>
        আমি কুমারজিৎ দত্ত। চট্টগ্রাম বিশ্ববিদ্যালয় কম্পিউটার বিজ্ঞান ও প্রকৌশল বিভাগের একজন প্রাক্তন ছাত্র। বর্তমানে রূপালী
        ব্যাংক লিমিটেডের আইসিটি সিস্টেমস বিভাগে সিনিয়র অফিসার (এসিসটেন্ট প্রোগ্রামার) হিসাবে নিযুক্ত আছি।
    </p>

    <p>
        এই সাইটটি চট্টগ্রামের করোনা চিকিৎসা সংক্রান্ত তথ্যসস তুলে ধরার এক ক্ষুদ্র প্রয়াস। দেশের এই দুর্যোগময় পরিস্থিতিতে আশা করি
        এই সাইটটি কিছুটা হলেও আপনাদের কাজে আসবে। সাইটটিতে পর্যাপ্ত পরিমাণে অথেন্টিক ডাটা প্রয়োজন বিধায় আপনাদের সহযোগিতা একান্ত কাম্য।
    </p>

    <p>
        সাইটটি সম্পর্কে যেকোন পরামর্শ, অভিযোগ, উপদেশ কিংবা করোনার চিকিৎসা সম্পর্কিত কোন তথ্য
        এই <a href="mailto:kumarjitdutta581@gmail.com">ই-মেইল এড্রেসে</a> পাঠিয়ে সাহায্য করুন অথবা ফেইসবুক ম্যাসেজ করতে পারেন এই লিংকেঃ <a href="https://www.facebook.com/kumarjit.dutta">ফেইসবুক লিংক</a>
    </p>
</div>

e_shastho/Views/Hospital/Create.cshtml
@using e_shastho.Data
@model Hospital
@{
    ViewData["Title"] = "করোনা সেবায় নিযুক্ত হাসপাতাল";
}


<div class="card-body">
    <h4 class="m-b-0">করোনা সেবায় নিযুক্ত হাসপাতাল</h4>

    @using (Html.BeginForm("Create", "Hospital", FormMethod.Post, new { @class = "form-horizontal m-t-40", enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <input type="hidden" name="Id" id="Id" value="0" />
            @Html.LabelFor(e => e.Name, "হাসপাতালের নাম", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Contact, "যোগাযোগ", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Contact, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Details, "বিস্তারিত", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Details, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Type, "প্রকার", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                <select class="form-control" name="Type" id="Type">
                    <option value="">Select</option>
                    <option value="Public">সরকারি</option>
                    <option value="Private">বেসরকারি</option>
                </select>
            </div>
        </div>



        <div class="form-group row">
            <label for="Address" class="col-sm-2 col-form-label">ঠিকানা</label>
            <div class="col-sm-10">
                <div class="col-12" style="float: right;padding-left:0px">
                    <fieldset class="gllpLatlonPicker">
                        <div class="row">
                            <div class="col-md-10">
                                <input type="text" class="form-control gllpSearchField" id="Address" name="Address">
                            </div>
                            <div style="text-align: right" class="col-md-2">
                                <input type="button" class="gllpSearchButton btn btn-danger btn-fill" value="search">
                            </div>
                        </div>
                        <br />

                        <div style="width: 100%" class="gllpMap">গুগল ম্যাপ</div>

                        <br />

                        <div class="row">
                            <div class="col-md-4">
                                <label class="control-label">Latitude:</label>
                                @Html.TextBoxFor(model => model.Latitude, htmlAttributes: new { @class = "form-control gllpLatitude", @Value = 22.356851 })
                                @*<input asp-for="Latitude" value="22.356851" id="Latitude" name="Latitude" class="form-control gllpLatitude" />*@
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">Longitude:</label>
                                @Html.TextBoxFor(model => model.Longitude, htmlAttributes: new { @class = "form-control gllpLongitude", @Value = 91.7831819 })
                                @*<input asp-for="Longitude" value="91.7831819" id="Longitude" name="Longitude" class="form-control gllpLongitude" />*@
                            </div>

                            <div class="col-md-3" style="display:none">
                                <label class="control-label">Zoom</label>
                                <input type="text" class="form-control gllpZoom" value="12" />
                            </div>
                            <div style="display:none" class="col-md-1">
                                <input type="button" class="gllpUpdateButton btn btn-danger btn-fill" value="Zoom">
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>


        <hr>
        <a class="btn waves-effect waves-light btn-rounded btn-secondary" href="@Url.RouteUrl("Hospitals")">Back to List</a>
        <button type="submit" value="Submit" class="btn btn-success  btn-rounded" style="float:right; margin-top:5px;"><i class="fas fa-save"></i> Create</button>

    }
</div>


@section Scripts{

    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyAkirniccOj_0KcRX4tqXih70MC3JIVUvA"></script>
    <!-- CSS and JS for our code -->
    <script src="~/Content/css/jquery-gmaps-latlon-picker.js"></script>
    <link href="~/Content/css/jquery-gmaps-latlon-picker.css" rel="stylesheet" />
}

e_shastho/Views/Hospital/Index.cshtml
@using e_shastho.Data
@model List<Hospital>

@{
    ViewData["Title"] = "করোনা সেবায় নিযুক্ত হাসপাতাল";
}

<div class="text-center">
    <h1>করোনা সেবায় নিযুক্ত হাসপাতাল</h1>
    <br />

    <p style="text-align:right">
        <a class="btn btn-info" href="@Url.RouteUrl("HospitalLocator")">গুগল ম্যাপে দেখুন</a>
        @*<a class="btn btn-info" asp-area="" asp-controller="Hospital" asp-action="Create">হাসপাতালের তথ্য সংরক্ষণ</a>*@
    </p>


    <table class="table table-hover">
        <thead>
            <tr>
                <th>নাম</th>
                <th>ঠিকানা</th>
                <th>যোগাযোগ</th>
                <th>ধরন</th>
                <th>অন্যান্য তথ্য</th>
            </tr>
        </thead>
        @if (!Model.Any())
        {
            <tbody>
                <tr>
                    <td colspan="5">ডাটা পাওয়া যায় নি</td>
                </tr>
            </tbody>
        }
        else
        {
            <tbody>
                @foreach (Hospital hospital in Model)
                {
                    <tr>
                        <td>@hospital.Name</td>
                        <td>@hospital.Address</td>
                        <td>@hospital.Contact</td>
                        @if (hospital.Type == "Public")
                        {
                            <td>সরকারি</td>
                        }
                        else
                        {
                            <td>প্রাইভেট</td>
                        }
                        <td>@hospital.Details</td>
                    </tr>
                }
            </tbody>
        }
    </table>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            $(".table").DataTable({
                responsive: true,
                columnDefs: [
                    { responsivePriority: 1, targets: 0 },
                    { responsivePriority: 2, targets: 1 },
                    { responsivePriority: 3, targets: 2 },
                    { responsivePriority: 4, targets: 3 },
                    { responsivePriority: 5, targets: 4 }
                ]
            });

            $(".dataTables_filter input").attr("placeholder", "সার্চ করুন");
        });


    </script>
}

e_shastho/Views/Hospital/MapLocator.cshtml
@using e_shastho.Data
@model List<Hospital>
@{
    ViewData["Title"] = "করোনা সেবায় নিযুক্ত হাসপাতাল";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
<style>
    * {
        margin: 0px;
        padding: 0px;
    }

    .parent {
        padding: 12px;
    }

    #main_map, .all_contact {
        height: 80vh;
    }

    .all_contact {
        overflow-y: scroll;
    }

    .leaflet-popup-close-button {
        display: none;
    }

    .contact_parent {
        font-size: 1.03em;
        padding: 12px;
        cursor: pointer;
        transition: all 0.2s;
    }

        .contact_parent:hover {
            background: rgb(240,240,240);
        }

        .contact_parent span {
            font-size: 1.1em;
            font-weight: bold;
        }

    .name_holder {
        font-size: 1.3em;
        font-weight: bold;
    }

    .contact_holder {
        font-size: 1.2em;
    }

    .popup_image {
        width: 100%;
        margin-bottom: 6px;
    }
</style>


<div class="text-center">
    <h1>করোনা সেবায় নিযুক্ত হাসপাতাল</h1>
    <br />

    <p style="text-align:right">
        <a class="btn btn-info" href="@Url.RouteUrl("Hospitals")">হাসপাতালের তালিকা</a>
        @*<a class="btn btn-info" asp-area="" asp-controller="Hospital" asp-action="Create">হাসপাতালের তথ্য সংরক্ষণ</a>*@
    </p>

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12">
                <div id="main_map">

                </div>
            </div>
            <div class="col-lg-4 col-md-12 col-sm-12">
                হাসপাতালের নামের উপর ক্লিক করুন
                <div class="all_contact">
                    @foreach (Hospital hospital in Model)
                    {
                        <div class="contact_parent">
                            <span>@hospital.Name</span><br />
                            @hospital.Contact
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts{

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
    <script>

				$(document).ready(function(){

					var map = L.map('main_map').setView([22.3663494,91.8204092], 12.5);
					L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
						attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
					}).addTo(map);

					var markers = {};

                    var hospitals = new Array();
                    var latitudes = new Array();
                    var longitudes = new Array();
                    var contacts = new Array();

                    @foreach (var d in Model)
                    {
                        @:hospitals.push("@d.Name");
                        @:latitudes.push("@d.Latitude");
                        @:longitudes.push("@d.Longitude");
                        @:contacts.push("@d.Contact");
                    }


                    for (var i = 0; i < hospitals.length; i++) {
						markers[i] = L.marker([latitudes[i],longitudes[i]]).addTo(map)
                            .bindPopup('<span class="name_holder">' + hospitals[i] + '</span><br/><span class="contact_holder">' +
                                contacts[i] + '</span>')
							.bindTooltip(hospitals[i]+"<br/>"+contacts[i]);

                        //console.log(hospitals[i].Name);
					}

					markers[0].openPopup();

					$(".contact_parent").click(function(){
						var the_index = $(".contact_parent").index($(this));
						markers[the_index].openPopup();
					});

				});

    </script>


}

e_shastho/Views/Info/Create.cshtml
@using e_shastho.Data
@model Advice

@{
    ViewData["Title"] = "তথ্য যোগ করুন";
}


<div class="card-body">
    <h4 class="m-b-0">তথ্য যোগ করুন</h4>

    @using (Html.BeginForm("Create", "Info", FormMethod.Post, new { @class = "form-horizontal m-t-40", enctype = "multipart/form-data" }))
    {

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            <input type="hidden" name="Id" id="Id" value="0" />
            @Html.LabelFor(e => e.Title, "শিরোনাম", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Title, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.AdvisorName, "তথ্য দাতার নাম ও বিস্তারিত", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.AdvisorName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Email, "তথ্য দাতার ইমেইল", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Email, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Reference, "তথ্য সোর্স", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Reference, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group row">
            @Html.LabelFor(e => e.Reference, "কন্টেন্ট", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextAreaFor(model => model.Content, new { @class = "form-control summernote", @rows = 5, required = "required" })
            </div>
        </div>

        <hr>
        <a class="btn waves-effect waves-light btn-rounded btn-secondary" href="@Url.RouteUrl("Information")">Back to List</a>
        <button type="submit" value="Submit" class="btn btn-success  btn-rounded" style="float:right; margin-top:5px;"><i class="fas fa-save"></i> Create</button>

    }
</div>


@section Scripts{

    <script>
        CKEDITOR.replace('Content');
    </script>
}

e_shastho/Views/Info/Details.cshtml
@using e_shastho.Data
@model Advice
@{
    ViewData["Title"] = "বিস্তারিত";
}

<p style="text-align:right">
    <a class="btn btn-info" href="@Url.RouteUrl("Information")">তথ্য তালিকায় ফেরত যান</a>
</p>

<div class="text-left">
    <h3 class="text-center">@Model.Title</h3>
    <hr />
    @Html.Raw(@Model.Content)
    <p>পোস্ট ক্রেডিটঃ @Model.AdvisorName</p>
    <p><a href=@Model.Reference>পোস্ট রেফারেন্স লিংক</a></p>
</div>

e_shastho/Views/PlasmaDonor/Create.cshtml
@using e_shastho.Data
@model PlasmaDonor
@{
    ViewData["Title"] = "প্লাজমা দাতার তথ্য সংরক্ষণ";
}


<div class="card-body">
    <h4 class="m-b-0">প্লাজমা দাতার তথ্য সংরক্ষণ</h4>

    @using (Html.BeginForm("Create", "PlasmaDonor", FormMethod.Post, new { @class = "form-horizontal m-t-40", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <input type="hidden" name="Id" id="Id" value="0" />
            @Html.LabelFor(e => e.Name, "দাতার নাম", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Address, "ঠিকানা", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Address, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Contact, "যোগাযোগ", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Contact, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.CoronaAffectedDate, "আক্রান্ত হওয়ার তারিখ", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.CoronaAffectedDate, new { @class = "form-control datepicker" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.RecoveryDate, "সুস্থ হওয়ার তারিখ", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.RecoveryDate, new { @class = "form-control datepicker" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.Email, "ইমেইল", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(e => e.Email, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(e => e.BloodGroup, "ব্লাড গ্রুপ", new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                <select class="form-control" name="BloodGroup" id="BloodGroup">
                    <option value="">Select</option>
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                </select>
            </div>
        </div>

        <hr>
        <a class="btn waves-effect waves-light btn-rounded btn-secondary" href="@Url.RouteUrl("PlasmaDonors")">Back to List</a>
        <button type="submit" value="Submit" class="btn btn-success  btn-rounded" style="float:right; margin-top:5px;"><i class="fas fa-save"></i> Create</button>

    }
</div>

e_shastho/Views/TestLocation/Index.cshtml
@using e_shastho.Data
@model List<TestLocation>

@{
    ViewData["Title"] = "নমুনা সংগ্রহ কেন্দ্রসমূহ";
}

<div class="text-center">
    <h1>নমুনা সংগ্রহ কেন্দ্রসমূহ</h1>
    <br />

    <p style="text-align:right">
        <a class="btn btn-info" href="@Url.RouteUrl("TestLocationLocator")">গুগল ম্যাপে দেখুন</a>
        @*<a class="btn btn-info" asp-area="" asp-controller="TestLocation" asp-action="Create">টেস্ট কেন্দ্রের তথ্য সংরক্ষণ</a>*@
    </p>


    <table class="table table-hover">
        <thead>
            <tr>
                <th>নাম</th>
                <th>ঠিকানা</th>
                <th>যোগাযোগ</th>
                <th>ধরন</th>
                <th>অন্যান্য তথ্য</th>
            </tr>
        </thead>
        @if (!Model.Any())
        {
            <tbody>
                <tr>
                    <td colspan="5">ডাটা পাওয়া যায় নি</td>
                </tr>
            </tbody>
        }
        else
        {
            <tbody>
                @foreach (TestLocation testLocation in Model)
                {
                    <tr>
                        <td>@testLocation.Name</td>
                        <td>@testLocation.Address</td>
                        <td>@testLocation.Contact</td>
                        @if (testLocation.Type == "Public")
                        {
                            <td>সরকারি</td>
                        }
                        else
                        {
                            <td>প্রাইভেট</td>
                        }
                        <td>@testLocation.Details</td>
                    </tr>
                }
            </tbody>
        }
    </table>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            $(".table").DataTable({
                responsive: true,
                columnDefs: [
                    { responsivePriority: 1, targets: 0 },
                    { responsivePriority: 2, targets: 1 },
                    { responsivePriority: 3, targets: 2 },
                    { responsivePriority: 4, targets: 3 },
                    { responsivePriority: 5, targets: 4 }
                ]
            });

            $(".dataTables_filter input").attr("placeholder", "সার্চ করুন");
        });
    </script>
}